apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-allocator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-allocator
  template:
    metadata:
      labels:
        app: cpu-allocator
    spec:
      containers:
      - name: cpu-allocator
        image: chandugogi/cpu-allocator:latest
        resources:
          requests:
            cpu: "500m"   # Requesting half a CPU core
          limits:
            cpu: "1"      # Limit to 1 CPU core

