# Base image
FROM ubuntu:20.04

# Install SSH, Python, and Flask
RUN apt-get update && apt-get install -y \
    openssh-server \
    python3 \
    python3-pip

# Install Flask
RUN pip3 install Flask

# Setup Flask app
RUN mkdir /app
COPY app.py /app/app.py

# Expose SSH and web server ports
EXPOSE 22 5000

# Setup SSH
RUN mkdir /var/run/sshd
RUN echo 'root:password' | chpasswd
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# Start SSH and Flask app
CMD service ssh start && python3 /app/app.py
