apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpu-node
  template:
    metadata:
      labels:
        app: gpu-node
    spec:
      containers:
      - name: gpu-container
        image: nvidia/cuda:12.6-base
        resources:
          limits:
            nvidia.com/gpu: 1

