apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gpu-user-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gpu-user-role
subjects:
- kind: User
  name: "user1"  # Replace with the username of the person you want to assign the role to
  apiGroup: rbac.authorization.k8s.io

