apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: jhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        image: jupyterhub/configurable-http-proxy:latest
        ports:
        - containerPort: 8000
        args:
          - "--default-target=http://jupyterhub:8081"

